[Python, Visually](https://johnfisher-ai.github.io/Python-Visual-Guides/) &nbsp;&rsaquo;&nbsp; [APIs and JSON](https://johnfisher-ai.github.io/Python-Visual-Guides/apis-and-json.html)

# What an API Is


## What you will be able to do

Name the parts of an API request and its response: the method, the endpoint, the parameters, the
headers, the body and the status code. Then send a request from Python, read the raw exchange, and
take the response apart.


## The idea

### The problem

Yesterday's temperature in Tromso, this morning's exchange rates, the open issues in a GitHub
repository: all of it is data held by somebody else's program, on somebody else's computer. You
cannot open their database, and you cannot import their code.

You could download the web page a person reads and pick the numbers out of its HTML. People did,
for years, and every redesign of the page broke every program reading it. The page was made for
eyes, and nothing promised a program that a number would stay where it was.

What a program needs is a way to ask another program a question in a form that program has agreed
to answer, and to receive data rather than decoration.

### What an API is

> An **API**, an application programming interface, is the set of requests a program agrees to
> accept and the responses it promises to send back. A **web API** carries them over **HTTP**, the
> protocol a browser uses to fetch pages. The client sends a **request** that names a **method**
> and a **resource**, and the server returns a **response** carrying a **status code**,
> **headers** and a **body**, which for most APIs is JSON.

### The vocabulary of an API

Every call to a web API is a request from the client and a response from the server, and the rest
of the vocabulary names their parts. This section is the map. The notebooks of this guide take the
parts in turn, and the last column of each table says where.

A **request** carries up to four things:

| Part | What it is | Example | Covered in depth in |
|---|---|---|---|
| Method | the verb: what the client asks the server to do | `GET` | **Sending Data** |
| URL | the address of the resource, with any query parameters | `/stations/tromso` | this notebook, and **Query Parameters** |
| Headers | extra information about the request, as `Name: value` pairs | `Accept: application/json` | **Headers and Content Types** |
| Body | data the client sends, when the method sends any | `{"name": "Narvik"}` | **Sending Data** |

A **response** carries three:

| Part | What it is | Example | Covered in depth in |
|---|---|---|---|
| Status code | three digits saying how the request went, sometimes called a response code | `200 OK`, `404 Not Found` | **Status Codes** |
| Headers | extra information about the response | `Content-Type: application/json` | **Headers and Content Types** |
| Body | the data itself, most often JSON | `{"id": "tromso", ...}` | **JSON in a Response** |

An address an API responds at is called an **endpoint**. The practice API in this guide has a
`/stations` endpoint for the whole collection of weather stations, and a `/stations/{id}` endpoint
for a single station, where `{id}` stands for the station's id.

The **methods**, also called verbs, say what a request is for:

| Method | Asks the server to | For example |
|---|---|---|
| `GET` | send back a resource, changing nothing | read a station |
| `POST` | create a new resource, or carry out an action | add a station |
| `PUT` | replace a resource with the body sent | replace a station's whole record |
| `PATCH` | change part of a resource | correct a station's latitude |
| `DELETE` | remove a resource | remove a station |

`GET` is by far the most common, and most requests in this notebook use it. The **Sending Data**
notebook takes up the other four, including why repeating a `PUT` or a `DELETE` is harmless while
repeating a `POST` is not.

**Parameters** are the values that make a request specific, and each kind travels in a different
place:

| Kind | Where it travels | Example | Covered in depth in |
|---|---|---|---|
| Path parameter | inside the path, naming a resource | `tromso` in `/stations/tromso` | this notebook |
| Query parameter | after `?` in the URL, as `name=value` pairs joined by `&` | `?start_date=2025-01-15` | **Query Parameters** |
| Header | among the request's headers | `Authorization: Bearer <token>` | **Authentication** |
| Body | in the body of a `POST`, `PUT` or `PATCH` request | `{"latitude": 69.65}` | **Sending Data** |

Status codes fall into five classes, and the first digit says which:

| Class | Means | Codes you will meet |
|---|---|---|
| `1xx` | information only, rarely seen by client code | `100 Continue` |
| `2xx` | the request worked | `200 OK`, `201 Created`, `204 No Content` |
| `3xx` | the resource is at another address, which clients usually follow on their own | `301 Moved Permanently`, `302 Found` |
| `4xx` | the request was wrong | `400 Bad Request`, `401 Unauthorized`, `404 Not Found`, `405 Method Not Allowed`, `429 Too Many Requests` |
| `5xx` | the server failed | `500 Internal Server Error`, `503 Service Unavailable` |

The **Status Codes** notebook takes them apart, the **Rate Limits** notebook deals with `429`, and
the **Errors and Retries** notebook covers which failures are worth trying again.

Three more terms come up often enough to name now. An *API key* or *token* identifies who is
calling, the subject of the **Authentication** notebook. A long answer is often split into pages,
called *pagination*, the subject of the **Pagination** notebook. And a *rate limit* caps how many
requests a client may send in a period, the subject of the **Rate Limits** notebook.

### Why it works that way

HTTP messages are plain text, which the first look below shows directly. A request starts with a
request line naming the method, the path and the protocol version. Its headers follow, a blank line
ends them, and the body comes after when there is one. A response has the same layout, starting
with a status line. Every HTTP tool, from a browser to the `requests` library, is a convenience for
writing and reading these messages.

Two consequences follow. The server never learns what language the client was written in, only
what request arrived, which is why a single API can serve Python, JavaScript and a phone app alike.
And every request stands alone: the server responds to what it was asked, and nothing carries over
to the next request unless a header carries it.

### Where you will meet this

Weather services, payment providers, cloud storage, GitHub and the language models behind AI tools
are all used through web APIs. `pip install` itself speaks HTTP to the Python Package Index. In
this library, the **Projects, End to End** guide includes an API project that pulls a live feed and
stores what arrives.

### The practice API

Most requests in this guide go to a small practice API that the Setup cell starts inside the
notebook itself. In Colab, that means on Colab's computer, and nothing runs on yours. It serves the
weather stations used in the **Files, Paths and Formats** and **Object-Oriented Python** guides,
and it gives every reader the same answers, which is what lets a notebook produce an error on
purpose. Where the real internet is the point, a notebook calls a real public service instead:
here, Open-Meteo's archive of past weather.

### What this notebook covers

- The vocabulary above, seen in real requests and responses
- The parts of a URL, and its query parameters by name
- A request and its response as plain text, sent over a raw connection
- Taking a response apart into its status line, headers and body, and the body into a dictionary
- The same exchange through `urllib.request`, the client built into Python
- A request for a resource that is not there, and a method its endpoint does not allow
- A collection and its members, reached with a path parameter
- A real API: three days of Tromso's temperatures from Open-Meteo, chosen with query parameters
- Four errors: a missing scheme, a closed port, a `404` that `urllib` raises, and HTML where JSON
  was expected

### A first look

Before any of the detail, here is the whole idea in a few lines. There is nothing to run yet: read
it, and read the output underneath it. Everything from Setup onward is where you start running
things, and the rest of the notebook takes this apart piece by piece.

```python
import socket

request = "GET /stations/tromso HTTP/1.1\r\nHost: 127.0.0.1:8765\r\nConnection: close\r\n\r\n"

with socket.create_connection(("127.0.0.1", 8765)) as conn:
    conn.sendall(request.encode())
    print(conn.makefile().read())
```

```
HTTP/1.1 200 OK
Server: PracticeAPI/1.0
Date: Sun, 01 Mar 2026 09:00:00 GMT
Content-Type: application/json
Content-Length: 73

{"id": "tromso", "name": "Tromso", "latitude": 69.65, "longitude": 18.96}
```

Your code, the client, sent a `GET` request for the resource `/stations/tromso`, with two headers
and no body. The server returned a response with the status code `200 OK`, four headers and a JSON
body. Every call in this guide is a request and a response of this shape, and an API is the
agreement about which requests a server accepts and what its responses contain.


## Setup

Six imports, the last of them the practice API.

- `json` turns a JSON body into Python values
- `socket` opens a raw connection, so a request and its response can be seen as the text they are
- `urllib.request` sends requests the ordinary way, and fetches the practice API's code when this
  notebook runs in Colab
- `Path` checks whether that code is already beside the notebook
- `urlsplit` takes a URL apart into its pieces, and `parse_qs` takes a query apart into its
  parameters
- `practice_api` is the server this guide talks to. `start()` runs it in the background, inside
  this notebook, and returns its address

`HTTPError` is imported later, in Common errors, the only section that uses it.


In [1]:
import json
import socket
import urllib.request
from pathlib import Path
from urllib.parse import parse_qs, urlsplit

PRACTICE_API = "https://raw.githubusercontent.com/johnfisher-ai/Python-Visual-Guides/main/notebooks/apis-and-json/practice_api.py"

if not Path("practice_api.py").exists():      # true in Colab, which starts with only the notebook
    urllib.request.urlretrieve(PRACTICE_API, "practice_api.py")

import practice_api

BASE = practice_api.start()
print("The practice API is running at", BASE)


The practice API is running at http://127.0.0.1:8765


## Worked examples

### The parts of a URL

`urlsplit` takes a URL apart without sending anything. Here is the address of a station on the
practice API.


In [2]:
parts = urlsplit(f"{BASE}/stations/tromso")

print("scheme:", parts.scheme)
print("host:  ", parts.hostname)
print("port:  ", parts.port)
print("path:  ", parts.path)


scheme: http
host:   127.0.0.1
port:   8765
path:   /stations/tromso


`127.0.0.1` is the address a computer uses to reach itself, and `8765` is the port the practice API
listens on, so this URL leads to the server Setup started. The path names the resource. It matches
the endpoint `/stations/{id}`, with `tromso` in place of `{id}`: `tromso` is a **path parameter**.

A real service's URL has the same parts, and usually query parameters as well. This one asks
Open-Meteo's archive for three days of Tromso's weather.


In [3]:
archive = ("https://archive-api.open-meteo.com/v1/archive"
           "?latitude=69.65&longitude=18.96&start_date=2025-01-15&end_date=2025-01-17"
           "&daily=temperature_2m_mean&models=era5")
parts = urlsplit(archive)

print("scheme:", parts.scheme)
print("host:  ", parts.hostname)
print("port:  ", parts.port)
print("path:  ", parts.path)
print("query: ", parts.query)


scheme: https
host:   archive-api.open-meteo.com
port:   None
path:   /v1/archive
query:  latitude=69.65&longitude=18.96&start_date=2025-01-15&end_date=2025-01-17&daily=temperature_2m_mean&models=era5


No port is written, so the scheme's standard port applies: 443 for `https`, 80 for `http`. `https`
is the same HTTP carried over an encrypted connection, so everything this notebook shows about
requests and responses holds for it too.

The query holds the **query parameters**. `parse_qs` splits it into their names and values:


In [4]:
for name, values in parse_qs(parts.query).items():
    print(f"{name:<11} {values[0]}")


latitude    69.65
longitude   18.96
start_date  2025-01-15
end_date    2025-01-17
daily       temperature_2m_mean
models      era5


Six query parameters choose the place, the dates, the measurement and the model. `parse_qs` gives
a list of values for every name, because a query may repeat a name, which is why the loop prints
`values[0]`. Typing a query by hand works here, and the **Query Parameters** notebook shows why real
code builds it from a dictionary instead.

### A request and its response, over a raw connection

A raw connection sends exactly the bytes you give it and returns exactly the bytes the server sends
back, with no library in between. `exchange` below does that and nothing more: it connects to the
practice API, sends a request, and reads the response until the server closes the connection.

The request has a request line, two headers, and the blank line that ends the headers. The request
line gives the method, `GET`, then the path, then the protocol version, and a `GET` request has no
body. Every line ends in `\r\n`, a carriage return and a line feed, as HTTP requires. `Host` names
the server being asked, and `Connection: close` asks it to close the connection after sending its
response, which is how `exchange` knows the response is complete.


In [5]:
host, port = urlsplit(BASE).hostname, urlsplit(BASE).port


def exchange(request):
    """Send a request as raw text, and return the raw text of the response."""
    with socket.create_connection((host, port)) as conn:
        conn.sendall(request.encode("utf-8"))
        return conn.makefile(encoding="utf-8").read()


lines = ["GET /stations/tromso HTTP/1.1", f"Host: {host}:{port}", "Connection: close"]
raw = exchange("\r\n".join(lines) + "\r\n\r\n")
print(raw)


HTTP/1.1 200 OK
Server: PracticeAPI/1.0
Date: Sun, 01 Mar 2026 09:00:00 GMT
Content-Type: application/json
Content-Length: 73

{"id": "tromso", "name": "Tromso", "latitude": 69.65, "longitude": 18.96}


Read the response from the top:

- `HTTP/1.1 200 OK` is the **status line**: the protocol version, the status code `200`, and the
  reason phrase `OK`, which is there for people.
- `Server`, `Date`, `Content-Type` and `Content-Length` are the **response headers**.
  `Content-Type` says the body is JSON, and `Content-Length` says how many bytes of body to expect.
- The blank line ends the headers.
- Everything after it is the **response body**.

The practice API always reports the same `Date`, so this output matches yours. A real server
reports the moment it responded.

### Taking a response apart

Every client library begins with this step. The headers end at the first blank line, and everything
after it is the body. Reading the connection as text turned every `\r\n` into `\n`, which is why
the split below is on `"\n\n"`.


In [6]:
head, body = raw.split("\n\n", 1)
status_line, *header_lines = head.splitlines()
headers = dict(line.split(": ", 1) for line in header_lines)

print("status line:", status_line)
print("headers:    ", headers)
print("body:       ", body)


status line: HTTP/1.1 200 OK
headers:     {'Server': 'PracticeAPI/1.0', 'Date': 'Sun, 01 Mar 2026 09:00:00 GMT', 'Content-Type': 'application/json', 'Content-Length': '73'}
body:        {"id": "tromso", "name": "Tromso", "latitude": 69.65, "longitude": 18.96}


The body is still a string. `json.loads`, from the **JSON on Disk** notebook in the **Files, Paths
and Formats** guide, turns it into Python values.


In [7]:
station = json.loads(body)

print(type(station).__name__, station)
print(station["name"], "is at", station["latitude"], station["longitude"])
print("Content-Length said", headers["Content-Length"], "and the body is", len(body.encode()), "bytes")


dict {'id': 'tromso', 'name': 'Tromso', 'latitude': 69.65, 'longitude': 18.96}
Tromso is at 69.65 18.96
Content-Length said 73 and the body is 73 bytes


`Content-Length` counts bytes, not characters, which is why the comparison encodes the body first.
Here the two agree because every character is ASCII. A body containing `ø` would have more bytes
than characters.

### The same exchange through `urllib.request`

Real code does not write requests by hand. `urllib.request`, part of Python's standard library,
writes the request, reads the response and takes it apart, and `urlopen` returns an object
carrying the pieces. The connection closes at the end of the `with` block, as a file would.


In [8]:
with urllib.request.urlopen(f"{BASE}/stations/tromso") as response:
    print("status: ", response.status, response.reason)
    print("type:   ", response.headers["Content-Type"])
    body = response.read()

print("body:   ", body)
print("as dict:", json.loads(body))


status:  200 OK
type:    application/json
body:    b'{"id": "tromso", "name": "Tromso", "latitude": 69.65, "longitude": 18.96}'
as dict: {'id': 'tromso', 'name': 'Tromso', 'latitude': 69.65, 'longitude': 18.96}


`read` returns the body as bytes, not a string, because a body can as easily be an image as text.
`json.loads` accepts bytes and decodes them as UTF-8, so the body goes straight in.

### Asking for a resource that is not there

A request for a station that does not exist still receives a complete, well-formed response. The
answer is no.


In [9]:
lines = ["GET /stations/atlantis HTTP/1.1", f"Host: {host}:{port}", "Connection: close"]
print(exchange("\r\n".join(lines) + "\r\n\r\n"))


HTTP/1.1 404 Not Found
Server: PracticeAPI/1.0
Date: Sun, 01 Mar 2026 09:00:00 GMT
Content-Type: application/json
Content-Length: 42

{"error": "no station with id 'atlantis'"}


The status code is `404 Not Found`, and the body says why, in JSON, so a program can read the
reason as well as the code. The connection worked and the server did its job; what failed was the
request, which is what every `4xx` code means. `urlopen` reports this differently, as an exception,
which Common errors shows.

### A method the endpoint does not allow

The method is the first word of the request line, and it changes what the request asks for. The
stations are reference data, and the practice API only lets you read them. Here is a `DELETE`
request for the same station:


In [10]:
lines = ["DELETE /stations/tromso HTTP/1.1", f"Host: {host}:{port}", "Connection: close"]
print(exchange("\r\n".join(lines) + "\r\n\r\n"))


HTTP/1.1 405 Method Not Allowed
Server: PracticeAPI/1.0
Date: Sun, 01 Mar 2026 09:00:00 GMT
Content-Type: application/json
Content-Length: 59
Allow: GET

{"error": "DELETE not allowed: the stations are read-only"}


`405 Method Not Allowed` is another `4xx`: the request was wrong, because this endpoint does not
accept `DELETE`. The `Allow` response header lists the methods it does accept, here only `GET`. A
real API refuses a method the same way. The **Sending Data** notebook sends `POST`, `PUT` and
`DELETE` requests to a part of the practice API that accepts them.

### A collection, and its members

Most APIs are laid out the same way. A plural noun names a collection, and an id after it names a
member of that collection. On the practice API, `/stations` is the collection's endpoint, and its
response gives a summary of every member.


In [11]:
with urllib.request.urlopen(f"{BASE}/stations") as response:
    stations = json.loads(response.read())

print(stations)


[{'id': 'bergen', 'name': 'Bergen'}, {'id': 'oslo', 'name': 'Oslo'}, {'id': 'svalbard', 'name': 'Svalbard'}, {'id': 'tromso', 'name': 'Tromso'}]


The detail for a station lives at its own endpoint, `/stations/{id}`, so reading all of it takes a
request per station, each with the station's id as the path parameter.


In [12]:
for summary in stations:
    with urllib.request.urlopen(f"{BASE}/stations/{summary['id']}") as response:
        station = json.loads(response.read())
    print(f"{station['name']:<9} {station['latitude']:>6} {station['longitude']:>6}")


Bergen     60.39   5.32
Oslo       59.91  10.75
Svalbard   78.22  15.65
Tromso     69.65  18.96


Four stations, five requests: the collection, then a member at a time. A short summary list plus a
request per detail is the layout you will meet most often, and the **Pagination** notebook deals
with collections too long to send in a single response.

### A real API: Open-Meteo

The practice API responds the same way for every reader, which is what a notebook needs. A real
service does the same job over the internet. Open-Meteo publishes weather data free for
non-commercial use, with no key to sign up for, and its archive holds past days. The query
parameters in `archive` choose what comes back, and asking for the ERA5 model by name fixes which
data answers. A day in January 2025 is long settled, so you will get the same numbers as below.

Weather data by [Open-Meteo.com](https://open-meteo.com/), under
[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/), from the ERA5 reanalysis. Generated using
Copernicus Climate Change Service information 2026.


In [13]:
with urllib.request.urlopen(archive, timeout=30) as response:
    print("status:", response.status, response.reason)
    print("type:  ", response.headers["Content-Type"])
    weather = json.loads(response.read())

print("keys:  ", sorted(weather))


status: 200 OK
type:   application/json; charset=utf-8
keys:   ['daily', 'daily_units', 'elevation', 'generationtime_ms', 'latitude', 'longitude', 'timezone', 'timezone_abbreviation', 'utc_offset_seconds']


The response has the same parts as the practice API's: a status code, headers, and a JSON body.
`generationtime_ms` is how long the server spent on the request, so it changes every time, which is
why this cell prints the keys and not the whole body.

`timeout=30` stops `urlopen` waiting forever for a slow server. The **Errors and Retries** notebook
covers what to do when the wait runs out.


In [14]:
daily = weather["daily"]
unit = weather["daily_units"]["temperature_2m_mean"]

for day, temperature in zip(daily["time"], daily["temperature_2m_mean"]):
    print(day, temperature, unit)


2025-01-15 4.6 °C
2025-01-16 6.4 °C
2025-01-17 7.1 °C


A dictionary of lists, matched by position: `time[0]` goes with `temperature_2m_mean[0]`. `zip`
pairs them, as the **Loops** notebook showed. The **JSON in a Response** notebook reaches into
deeper structures than this.

### Two APIs, one question

The practice API knows where every station is. Open-Meteo knows what the weather was there. Asking
both, a station at a time, answers a question neither can answer alone.


In [15]:
def mean_temperatures(latitude, longitude):
    """Three daily mean temperatures for one place, from Open-Meteo's archive."""
    url = ("https://archive-api.open-meteo.com/v1/archive"
           f"?latitude={latitude}&longitude={longitude}"
           "&start_date=2025-01-15&end_date=2025-01-17&daily=temperature_2m_mean&models=era5")
    with urllib.request.urlopen(url, timeout=30) as response:
        return json.loads(response.read())["daily"]["temperature_2m_mean"]


with urllib.request.urlopen(f"{BASE}/stations") as response:
    stations = json.loads(response.read())

for summary in stations:
    with urllib.request.urlopen(f"{BASE}/stations/{summary['id']}") as response:
        station = json.loads(response.read())
    print(f"{station['name']:<9}", mean_temperatures(station["latitude"], station["longitude"]))


Bergen    [7.8, 8.0, 8.0]


Oslo      [0.0, 2.3, 3.0]


Svalbard  [-12.9, -12.8, -13.8]


Tromso    [4.6, 6.4, 7.1]


### Where each part came from

| In the loop | What it relies on | The section that showed it |
|---|---|---|
| `f"{BASE}/stations"`, then `/stations/{id}` | a collection's endpoint, then a member reached with a path parameter | A collection, and its members |
| `urlopen` in a `with` block | `urllib` sends the request and reads the response | The same exchange through `urllib.request` |
| `json.loads(response.read())` | the response body arrives as bytes of JSON | The same exchange through `urllib.request` |
| `?latitude=...&longitude=...` | query parameters, filled in from the practice API's response | The parts of a URL |
| `timeout=30` | a real server can be slow to respond | A real API: Open-Meteo |
| `["daily"]["temperature_2m_mean"]` | the response body is a dictionary of lists | A real API: Open-Meteo |

Nine requests to two servers, all sent with the same `urlopen`. The client does not need to know
who is responding, only the endpoint and the shape of the response.


## Your turn

Six tasks. Write your answer in the cell under each task and run it.

Try a task before you look at its answer. Reading a solution teaches you much less than getting
there yourself, even slowly.

When you are ready: [**open the solutions notebook**](https://colab.research.google.com/github/johnfisher-ai/Python-Visual-Guides/blob/main/notebooks/apis-and-json/01-what-an-api-is-solutions.ipynb).

**1.** Use `urlsplit` and `parse_qs` to print the path of `archive` and the value of its
`end_date` query parameter.


In [16]:
# your code here


**2.** Use `exchange` to send a `POST` request to `/stations`, and print the status line and the
`Allow` header of the response.


In [17]:
# your code here


**3.** Use `urlopen` to fetch `/stations`, and print how many stations the practice API has.


In [18]:
# your code here


**4.** Use `urlopen` to fetch `/stations/bergen`, turn the body into a dictionary, and print the
station's name, latitude and longitude on one line.


In [19]:
# your code here


**5.** Use `exchange` to request `/stations/narvik`, which does not exist. Split the response at the
blank line that ends the headers, and print the status line and the `error` field of the body.


In [20]:
# your code here


**6.** Ask Open-Meteo for Bergen's three daily mean temperatures, for the same dates as the
notebook, using the latitude and longitude from task 4, and print them.


In [21]:
# your code here


## Common errors

### URLError: unknown url type, when the scheme is missing

A URL without `http://` looks harmless, especially when it is an address and a port.


In [22]:
urllib.request.urlopen("127.0.0.1:8765/stations")


URLError: <urlopen error unknown url type: 127.0.0.1>

`unknown url type: 127.0.0.1` looks like nonsense until you see what `urllib` did: it read
everything before the first colon as the scheme, so it went looking for a protocol called
`127.0.0.1`. Every URL passed to `urlopen` needs its scheme. `BASE` starts with `http://`, which is
why building on it avoids this.


In [23]:
with urllib.request.urlopen(f"{BASE}/stations") as response:
    print(response.status, response.reason)


200 OK


### URLError: Connection refused, when nothing is listening


In [24]:
urllib.request.urlopen("http://127.0.0.1:8799/stations")


URLError: <urlopen error [Errno 61] Connection refused>

Read the last line first: `Connection refused`. The computer at `127.0.0.1` answered, and said no
program was listening on port `8799`, so the connection failed before any request was sent. The
traceback is long because the error passed through several layers on its way out: the first
exception, `ConnectionRefusedError`, comes from the connection itself, and `urlopen` raised the
`URLError` below it while handling that.

The number in brackets is the operating system's code for the failure: 61 on macOS, where this
notebook's output was recorded, and 111 on Linux, which is what Colab runs. The words are the same.

The usual causes are a mistyped port and a server that is not running, which here would mean Setup
was not run. Print the address you meant to use, and compare:


In [25]:
print("the practice API is at", BASE)

with urllib.request.urlopen(f"{BASE}/stations") as response:
    print(response.status, response.reason)


the practice API is at http://127.0.0.1:8765
200 OK


### HTTPError: HTTP Error 404, which urlopen raises

Earlier, a raw request for this station received a complete `404` response. `urlopen` treats that
response differently.


In [26]:
urllib.request.urlopen(f"{BASE}/stations/atlantis")


HTTPError: HTTP Error 404: Not Found

`urlopen` turns any status code of 400 or above into an exception. The exception carries the
response, so catch it and read the status code and the body from it. `HTTPError` lives in
`urllib.error`:


In [27]:
from urllib.error import HTTPError

try:
    urllib.request.urlopen(f"{BASE}/stations/atlantis")
except HTTPError as error:
    print("status:", error.code, error.reason)
    print("body:  ", json.loads(error.read()))


status: 404 Not Found
body:   {'error': "no station with id 'atlantis'"}


The `requests` library in the **Your First Request** notebook makes the opposite choice: a `404`
comes back as an ordinary response, and raises only when you ask it to.

### JSONDecodeError: the body was HTML, not JSON

The practice API's home page, at `BASE` itself, is written for people.


In [28]:
with urllib.request.urlopen(BASE) as response:
    body = response.read()

json.loads(body)


JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`Expecting value: line 1 column 1 (char 0)` means the very first character was not the start of
any JSON value. It was `<`, the start of an HTML tag. Real code meets this when a URL is slightly
wrong and the server responds with a web page, or when a proxy between you and the server returns
an error page of its own. Check `Content-Type` before parsing:


In [29]:
with urllib.request.urlopen(BASE) as response:
    kind = response.headers["Content-Type"]
    body = response.read()

if kind.startswith("application/json"):
    print(json.loads(body))
else:
    print("not JSON:", kind)
    print(body.decode().splitlines()[0])


not JSON: text/html; charset=utf-8
<!doctype html>


## Recap

- An API is the set of requests a program agrees to accept and the responses it promises to send
  back. A web API carries them over HTTP.
- A request carries a method, a URL, headers, and sometimes a body. A response carries a status
  code, headers, and usually a body.
- The method is the verb: `GET` reads, `POST` creates, `PUT` replaces, `PATCH` changes part, and
  `DELETE` removes. An endpoint that does not accept a method responds with `405` and an `Allow`
  header.
- Parameters travel in the path (`/stations/tromso`), in the query (`?start_date=2025-01-15`), in
  headers, or in the body.
- The first digit of a status code gives its class: `2xx` worked, `4xx` means the request was
  wrong, and `5xx` means the server failed.
- Underneath, a request and a response are plain text: a first line, headers, a blank line, and a
  body. `urlsplit` and `parse_qs` take a URL apart, and `json.loads` turns a JSON body into Python
  values.
- A `404` is a complete response from a working server. `urlopen` raises `HTTPError` for it, and
  the exception carries the response.
- `Connection refused` means nothing was listening on that port, so no request was ever sent.
- Check `Content-Type` before parsing a body as JSON.


## What is next

The **Your First Request** notebook. `urlopen` did the job here, with some effort: bytes to decode,
and an exception for every `404`. The `requests` library, which most Python code uses, sends the
same request in one call and returns a response object carrying the status code, the headers and
the body, already decoded.


---

[APIs and JSON Notebooks](https://johnfisher-ai.github.io/Python-Visual-Guides/apis-and-json.html)
